.travis.yml
language: php

php:
- 5.5
- 5.6
- 7.0
- hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover

notifications:
  slack:
    secure: GLAz8cc60i+a7DiXrFqoThKPaSOpNbcCiqjSur8LuBPCtxWMfBFEKsmE7iweAe5fLUTffx4TbMbMd38LS/3hwpt5oYOoQBQ8IQDNtFJ7rbLkGtC6SI6lrPTWdBDfTyHevG4aOJZCiFe5+Tajvj2CWD+YAMcGaCn6s8IVLU5NoPw=
---
# Adapted from
# - https://github.com/drhelius/travis-ansible-demo/blob/master/.travis.yml
# - https://github.com/geerlingguy/ansible-role-docker/blob/master/.travis.yml
language: python
services:
  - docker

env:
  global:
    - ANSIBLE_ROLE: quantum_mobile_customizations

matrix:
  include:
    - name: Ubuntu-18.04
      env:
        - DOCKER_IMAGE: marvelnccr/ubuntu-docker-base
        - DOCKER_IMAGE_VERSION: 2.2
        - ANSIBLE_USER: ubuntu
    - name: Ubuntu-16.04
      env:
        - docker_image: marvelnccr/ubuntu-docker-base
        - version: 1.1
        - ansible_user: ubuntu

install:
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-quantum-mobile-customizations marvel-nccr.$ANSIBLE_ROLE
  - cd marvel-nccr.$ANSIBLE_ROLE

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
