<# Skip to content
 
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 @oscarg933 Sign out
You are over your private repository plan limit (4 of 0). Please upgrade your plan, make private repositories public, or remove private repositories so that you are within your plan limit.
Your private repositories have been locked until this is resolved. Thanks for understanding. You can contact support with any questions.
0
0 5 oscarg933/ICErepo
forked from mattpass/ICErepo
 Code  Pull requests 0  Projects 0  Wiki  Insights  Settings
Show diffs, push, pull & sync your site with Github repos
 141 commits
 1 branch
 20 releases
 2 contributors
 View license
 JavaScript 65.3%	 PHP 26.3%	 CSS 8.4%
 Pull request   Compare This branch is even with mattpass:master.
@mattpass
mattpass Merge pull request mattpass#16 from marclaporte/patch-1  …
Latest commit d0aa055  a day ago
Type	Name	Latest commit message	Commit time
images	Icons reupload	5 years ago
lib	Full unminifed version	6 years ago
.gitignore	Don't commit errors to the repo	6 years ago
LICENSE.md	Copyright 2014	5 years ago
README.md	Fix some typos	2 months ago
contents.php	Consider .gitignore and .git	5 years ago
file-control.php	new & deleted reversed, show msg on 0 counts	5 years ago
ice-repo.css	Fatter select, smaller checkboxes	5 years ago
ice-repo.js	3 x no files hidden displays added	5 years ago
index.php	Bug fixes & tweaks	5 years ago
php.ini	Attempt to turn off magic quotes	6 years ago
settings.php	Version 1.0 beta	5 years ago
 README.md
ICErepo
Show diffs, push, pull & sync your site and Github repo's.

While Github has a fantastic website, mobile app, desktop app and of course bash system, there's no web based UI I can find to sync your website code with Github repo's or vice versa. That's what ICErepo provides.

Originally intended to be a plugin for ICEcoder (https://github.com/mattpass/ICEcoder), I have decided to make it a standalone lib so it can run by itself or easily be integrated into any existing system.

The aim is a simple UI to view diffs between your server dir's and related Github repo's. This list will consist of new files (those only on server), deleted files (those only on Github) and changed files (files that exist in both places but are different). Files that exist in both locations and the same are not shown to keep things minimalist.

Users can then to pick & choose the files they'd like to commit, provide a title and message, then commit to Github. As each file is synced by the user to match the server it disappears from the UI list. Alternatively you can pull files & folders from Github to sync your server dir's with the repo itself.

Cool huh?

Current screenshot:

ICErepo screenshot

This lib uses customised & minified versions of these brilliant and time tested repos:

Github API lib: https://github.com/michael/github

JS Diff lib: https://github.com/cemerick/jsdifflib

###Installation

####Step 1: Clone the repo

$ git clone git://github.com/mattpass/ICErepo
####Step 2: Enter your auth settings

Open settings.php and enter either your Github oauth token or username & password
oauth is the better choice of the two here, view http://developer.github.com/v3/oauth/ for info
(If using oauth ensure you have repo scope & your app is granted the URL you'll run under). You can also omit entering any details here and it will ask for either of these details to use in the session. A token set in the session is the recommended approach here.
####Step 3: Enter your repo & server dir settings

Also in settings.php, enter the repo & corresponding server paths
Enter 'selected' as a 3rd param next to your default repo/server option to autoload that
Finally, set $_SESSION['userLevel'] to be > 0 with your own login system
Upload ICErepo, visit in a web browser & enjoy
© 2018 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
Press h to open a hovercard with more details.
